import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';

const About = () => {
  return (
    <>
        <Container style={{marginTop:'50px'}}>
            <h1>Qui sommes-nous ?</h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo quasi obcaecati magnam voluptas quisquam vel consequuntur tempore nisi doloremque pariatur. Aliquid, inventore tempora, consectetur vitae quaerat repellendus quod perspiciatis illum temporibus voluptas eaque incidunt possimus. Ipsam cumque laboriosam quis omnis alias culpa mollitia eius numquam, pariatur aut. Accusantium, cum voluptatibus maiores assumenda minus atque quod quo ea ullam voluptates odit, velit officiis temporibus? A soluta animi omnis vero mollitia perferendis repellendus ea quod fuga atque in exercitationem consequatur expedita, molestias quis delectus facilis quidem assumenda quia asperiores obcaecati! Nostrum delectus fugiat repellendus inventore totam voluptates culpa sunt aliquid aperiam quidem dignissimos in quos, expedita ullam unde, doloremque praesentium odit porro amet excepturi veritatis quasi. Accusantium tenetur ducimus, repudiandae sunt nesciunt optio! Odio ea unde quam architecto, in quo corrupti, iure molestiae itaque libero, amet voluptatem. Inventore commodi iure dicta reprehenderit? Repellendus blanditiis molestiae dolorem atque quidem odit doloremque optio mollitia, modi tempora qui amet aspernatur nisi iure enim fuga numquam error illo labore ex suscipit quia minima distinctio? Numquam provident quidem accusantium molestias deleniti. Nesciunt reprehenderit magnam in sit iusto sapiente dolores atque placeat sed, possimus ut quis autem optio dignissimos! Blanditiis cupiditate sunt nobis, impedit earum tempora nisi incidunt.</p>
            <h1>Notre spécialité</h1>
            <Row>
                <Col md={6}>
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veniam saepe fugit recusandae deserunt exercitationem numquam nostrum laudantium! Reiciendis voluptates quo repellendus amet laudantium, explicabo cum officiis voluptatum! Voluptate deleniti quidem facilis. Maiores tempora cupiditate ea ab voluptatum veniam eos aperiam sequi, a suscipit deleniti minus rerum, alias harum quo magnam nulla? Rem, nihil! Numquam libero magni dolore quas suscipit. Cumque a harum animi eveniet quibusdam aliquam nulla, totam temporibus accusantium! Aliquam debitis veritatis unde in inventore obcaecati praesentium incidunt, molestiae voluptate ex laudantium natus nulla non rerum! Minima impedit numquam recusandae temporibus sunt obcaecati veniam quia! Odio veniam voluptas id beatae dolor eligendi eos voluptate asperiores, harum nisi nihil rerum aliquid iusto fugiat, officia a maxime magnam quasi minus fugit. Sed quidem rem voluptas, obcaecati, explicabo ipsum ad beatae suscipit, asperiores repellat vel possimus delectus similique officiis quod minima aperiam consequuntur? Itaque molestiae officiis dolores quam modi ipsum sapiente accusantium! Enim, est unde ad officiis quae alias eos ducimus harum rem vero maiores sed molestiae ipsa minima commodi expedita eaque laudantium quisquam aperiam cupiditate iure earum accusantium! Facilis cum tenetur possimus deserunt quos libero, nesciunt magnam natus illum voluptatem modi dolore accusamus blanditiis vel quaerat rem eaque pariatur tempore cupiditate.</p>
                </Col>
                <Col md={6}>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eos iure quo qui impedit, labore at, itaque quos totam veniam maxime perferendis reiciendis! Cupiditate officia ad libero a quae dicta blanditiis, labore harum atque non aliquid eligendi modi. Aut nam omnis placeat porro excepturi deserunt enim dicta, dolore cupiditate ipsa esse accusamus harum neque modi? Error debitis atque aperiam perferendis corrupti a, saepe dicta necessitatibus libero sapiente reiciendis aspernatur iure quos quam suscipit quis placeat, impedit laudantium quod illum odit assumenda ipsam. In consequatur ex architecto quod, alias quisquam possimus ab quo eaque natus porro vitae a, adipisci harum deserunt officia laboriosam, earum sunt molestiae expedita. Quod odio necessitatibus impedit beatae velit ut sint soluta recusandae voluptatem neque? Tempore veniam debitis fugiat cum corporis explicabo ullam aspernatur commodi culpa atque cupiditate quod dolores quo nam, dolorum libero consequuntur est exercitationem sunt sed incidunt qui error perspiciatis. Repellat harum beatae mollitia consectetur. Sapiente distinctio magni ea quibusdam deserunt consequatur optio laboriosam recusandae aliquam. Neque earum at porro pariatur deleniti inventore iusto, accusantium repudiandae sit dolor qui ea architecto, quia repellendus. Quidem facilis nobis, ducimus ea provident dolor nisi est dolorum rerum cum ratione possimus laudantium ab! Quos iste repudiandae veritatis ea necessitatibus.</p>
                </Col>
            </Row>
            <Row>
                <h1>Le Chef</h1>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto hic natus veritatis eius consectetur blanditiis assumenda, cumque nemo enim quo itaque quis laborum, error quisquam accusamus sit, ipsam iste amet. Quam dignissimos dolore dolorum impedit laboriosam illum laudantium eos, nemo suscipit magnam error ad, modi, commodi totam quasi eveniet maxime nulla distinctio nihil molestias cupiditate porro est veniam. Voluptate odio at magnam cum a consectetur sed vero animi velit alias, fugit dolores ad nemo omnis corrupti quis cumque ea nostrum ipsa doloribus autem itaque delectus iure accusantium! Incidunt voluptatibus minus ipsam nemo veritatis ex mollitia illo minima recusandae temporibus, architecto ab rerum molestias laborum dolor.</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias iste amet numquam cumque? Quam facilis recusandae facere sed blanditiis fuga ipsa quidem ratione unde architecto reiciendis, sequi inventore placeat itaque ducimus cumque? Corporis quod cum amet vero, minus unde quasi fugiat. Nam rerum sapiente qui distinctio ratione sequi quam quibusdam. Reiciendis facere aspernatur qui eius inventore, quibusdam dolorem nam voluptatum quidem alias minima quod esse quia accusamus repudiandae, corporis iure modi! Dicta fugiat odio culpa accusantium suscipit aperiam quam illum explicabo sed. Adipisci iusto esse totam quasi repellat officia pariatur laudantium unde, id voluptatibus quidem cum laboriosam eveniet maiores ratione repellendus vel magni porro accusantium?</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, voluptate neque? Sint nobis similique in deleniti eos quidem inventore quia placeat saepe fuga voluptatem quibusdam repudiandae, natus molestiae labore fugit consequuntur laboriosam aperiam iste earum rem. Error magni obcaecati praesentium, suscipit tempora quia totam et cumque libero laboriosam necessitatibus a maxime unde consequuntur, qui, ipsa neque quos. Rem dolore tenetur ad earum vel ut dicta possimus deleniti alias sed architecto excepturi voluptate quod numquam nostrum, assumenda harum ratione ab. Aliquam modi, suscipit saepe, explicabo deserunt facere laudantium quia eligendi cum nesciunt consectetur ex, adipisci eos a provident pariatur non porro.</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus dolorum molestias iste ad, reiciendis animi vero doloribus perspiciatis soluta eligendi magnam dolor hic aliquid quidem illo esse, impedit laboriosam amet! Iste quisquam beatae esse a eum, sint nostrum aliquid qui asperiores totam dignissimos enim consequatur deleniti voluptates ad cumque necessitatibus! Impedit alias similique assumenda ut facilis quidem molestiae vero officiis odit ipsam rerum autem sed, itaque repellendus reprehenderit, dolores voluptates. Quasi commodi ad, eligendi sunt aliquid, nam vitae magni quo maiores quaerat at? Nesciunt recusandae at obcaecati similique quia architecto veritatis cumque nam, eveniet saepe voluptatum, laudantium, quod labore repellendus.</p>
                </Col>
            </Row>
        </Container>
    </>
  )
}

export default About