Use SDBM

CREATE TABLE COULEUR
(
	ID_COULEUR integer AUTO_INCREMENT NOT NULL,
	NOM_COULEUR varchar(25) NOT NULL,
	CONSTRAinteger PK_COULEUR PRIMARY KEY CLUSTERED 
	(
		ID_COULEUR ASC
	)
) 

CREATE TABLE CONTINENT
(
	ID_CONTINENT integer AUTO_INCREMENT NOT NULL,
	NOM_CONTINENT varchar(25) NOT NULL,
	CONSTRAinteger PK_CONTINENT PRIMARY KEY CLUSTERED 
	(
		ID_CONTINENT ASC
	)
)

CREATE TABLE PAYS
(
	ID_PAYS integer AUTO_INCREMENT NOT NULL,
	NOM_PAYS varchar(40) NOT NULL,
	ID_CONTINENT integer NOT NULL,
	CONSTRAinteger PK_PAYS PRIMARY KEY CLUSTERED 
	(
		ID_PAYS ASC
	)
)

CREATE TABLE TYPEBIERE
(
	ID_TYPE integer AUTO_INCREMENT NOT NULL,
	NOM_TYPE varchar(25) NOT NULL,
	CONSTRAinteger PK_TYPEBIERE PRIMARY KEY CLUSTERED 
	(
		ID_TYPE ASC
	)
)

CREATE TABLE FABRICANT
(
	ID_FABRICANT integer AUTO_INCREMENT NOT NULL,
	NOM_FABRICANT varchar(40) NOT NULL,
	CONSTRAinteger PK_FABRICANT PRIMARY KEY NONCLUSTERED 
	(
		ID_FABRICANT ASC
	)
) 

CREATE TABLE MARQUE
(
	ID_MARQUE integer AUTO_INCREMENT NOT NULL,
	NOM_MARQUE varchar(40) NOT NULL,
	ID_PAYS integer NOT NULL,
	ID_FABRICANT integer NULL,
	CONSTRAinteger PK_MARQUE PRIMARY KEY NONCLUSTERED 
	(
		ID_MARQUE ASC
	)
) 


ALTER TABLE MARQUE  WITH CHECK ADD CONSTRAinteger FK_MARQUE_FABRICANT FOREIGN KEY(ID_FABRICANT)
REFERENCES FABRICANT (ID_FABRICANT)

ALTER TABLE MARQUE  WITH CHECK ADD CONSTRAinteger FK_MARQUE_PAYS FOREIGN KEY(ID_PAYS)
REFERENCES PAYS (ID_PAYS)


ALTER TABLE PAYS  WITH CHECK ADD  CONSTRAinteger FK_PAYS_CONTINENT FOREIGN KEY(ID_CONTINENT)
REFERENCES CONTINENT (ID_CONTINENT)


